services:
  postgresql:
    container_name: postgresql
    image: postgres:17.6
    ports:
      - "5541:5541"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    env_file: .env.pg
    environment:
      PGPORT: 5541
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "supertokens-user", "-d", "supertokens-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  supertokens:
    container_name: supertokens
    image: registry.supertokens.io/supertokens/supertokens-postgresql:11.1.0
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 5542:5542
    env_file: .env.st
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/5542 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:5542\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    ports:
      - "5543:5543"
      - "5544:5544"
    env_file: .env.minio
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":5544"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5544/minio/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:

networks:
  app_network:
    driver: bridge
